"""
Django settings for Django_Demo project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p+da770chxu5-pg5006_iy*q=5q-%a=5=@a7=_ley*1y3a6sz2'

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com']


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Demo',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     "https://jzvzvq.zid.store",
#     "https://zid.store"
# ]

CORS_ALLOW_CREDENTIALS = True

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'Django_Demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Demo' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_Demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False

DEBUG = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/login/'

LOGIN_URL = '/login/'

BACKEND_URL = 'https://zid-sleepy-test.onrender.com'

ZID_AUTH_URL = 'https://oauth.zid.sa/oauth/authorize'
ZID_TOKEN_URL = 'https://oauth.zid.sa/oauth/token'
ZID_API_BASE = 'https://api.zid.sa/v1'

ZID_CLIENT_ID = os.environ.get('ZID_CLIENT_ID')
ZID_CLIENT_SECRET = os.environ.get('ZID_CLIENT_SECRET')
ZID_REDIRECT_URI = 'https://zid-sleepy-test.onrender.com/callback'

SESSION_COOKIE_AGE = 24*3600  # 1 day
SESSION_SAVE_EVERY_REQUEST = True

# settings.py
OAUTH_PROVIDERS = {
    "google": {
        "client_id": "...",
        "client_secret": "...",
        "redirect_uri": "https://yourapp.com/oauth/google/callback/",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scope": "openid email profile",
    },
    "facebook": {
        "client_id": "...",
        "client_secret": "...",
        "redirect_uri": "https://yourapp.com/oauth/facebook/callback/",
        "auth_url": "https://www.facebook.com/v18.0/dialog/oauth",
        "token_url": "https://graph.facebook.com/v18.0/oauth/access_token",
        "scope": "email,public_profile",
    },
    "tiktok": {
        "client_id": "...",
        "client_secret": "...",
        "redirect_uri": "https://yourapp.com/oauth/tiktok/callback/",
        "auth_url": "https://www.tiktok.com/v2/auth/authorize/",
        "token_url": "https://open.tiktokapis.com/v2/oauth/token/",
        "scope": "user.info.basic,video.list",
    },
    "snapchat": {
        "client_id": "b9312a42-dc70-4dde-9cce-515e4dd3bcb2",
        "client_secret": "760a09521ee7ed47e84d",
        "redirect_uri": "https://zid-sleepy-test.onrender.com/oauth/snapchat/callback",
        "auth_url": "https://accounts.snapchat.com/login/oauth2/authorize",
        "token_url": "https://accounts.snapchat.com/login/oauth2/access_token",
        "scope": "snapchat-profile-api snapchat-marketing-api snapchat-offline-conversions-api"
    },
}
SNAPCHAT_CLIENT_ID = "ff633b59-bba4-4661-9f22-5178e6f1529a"
SNAPCHAT_CLIENT_SECRET = "21b8b156f26731290105"
SNAPCHAT_REDIRECT_URI = "https://zid-sleepy-test.onrender.com/oauth/snapchat/callback"
SNAPCHAT_OAUTH_SCOPE = "snapchat-profile-api snapchat-marketing-api snapchat-offline-conversions-api"

# SNAPCHAT_CLIENT_ID = "4f9c1908-b9ec-4440-a5c4-9b038fcb95b4"
# SNAPCHAT_CLIENT_SECRET = "HNFS0DJwUtGiJKhfI2eKY_JxkhEo-ic0vGeDjLal1UM"

TIKTOK_CLIENT_KEY = "your-app-id"
TIKTOK_CLIENT_SECRET = "your-app-secret"
TIKTOK_REDIRECT_URI = "https://zid-sleepy-test.onrender.com/oauth/tiktok/callback/"
TIKTOK_ADVERTISER_ID = "your-advertiser-id"
TIKTOK_OAUTH_SCOPE = "user.info.basic,video.list,video.upload,ad.account,ad.campaign,ad.adgroup,ad.ad,report.campaign,report.adgroup,report.ad"