"""
Django settings for Django_Demo project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os 
import re

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p+da770chxu5-pg5006_iy*q=5q-%a=5=@a7=_ley*1y3a6sz2'

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Demo',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware"
]

# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https://.*\.zid\.store$",
# ]
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True
# Disable CORS for everything by default -- allow only for selected routes



STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'Django_Demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Demo' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_Demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True
    )
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False

DEBUG = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/login/'

LOGIN_URL = '/login/'

ZID_AUTH_URL = 'https://oauth.zid.sa/oauth/authorize'
ZID_TOKEN_URL = 'https://oauth.zid.sa/oauth/token'
ZID_API_BASE = 'https://api.zid.sa/v1'

ZID_CLIENT_ID = os.environ.get('ZID_CLIENT_ID')
ZID_CLIENT_SECRET = os.environ.get('ZID_CLIENT_SECRET')
ZID_REDIRECT_URI = 'https://testing-within.onrender.com/zid/callback'
# Webhook Specific
TARGET_URL_PRODUCT_HOOK = 'https://testing-within.onrender.com/zid-webhook/product-update/'
ZID_WEBHOOK_ENDPOINT = "/v1/managers/webhooks"
ZID_API_HOST = "api.zid.sa"

## Webhooks
'''TARGET_URL_PRODUCT_HOOK = 'https://translation-sc.onrender.com/product-update'
TARGET_URL_ORDER_HOOK = 'https://translation-sc.onrender.com/order-update'
ZID_WEBHOOK_ENDPOINT = "/v1/managers/webhooks"
ZID_API_HOST = "api.zid.sa"'''


# Sessions
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_SAVE_EVERY_REQUEST = True


META_APP_ID = "1435524447520642"
META_APP_SECRET = "4bdfbeccf61ccd2ef92c47eff6ea306c"
META_REDIRECT_URI = "https://testing-within.onrender.com/meta/callback/"  # must match in Meta dev settings
META_OAUTH_SCOPE = "ads_management,ads_read,business_management,pages_show_list"  # adjust as needed

TIKTOK_CLIENT_KEY = "7551247511634051088"
TIKTOK_CLIENT_SECRET = "fef07eae0ea6ed64c02baa5c33f2d3a653877746"
TIKTOK_REDIRECT_URI = "https://testing-within.onrender.com/oauth/tiktok/callback/"
TIKTOK_OAUTH_SCOPE = "user.info.basic,video.list,video.upload,ad.account,ad.campaign,ad.adgroup,ad.ad,report.campaign,report.adgroup,report.ad"

SNAPCHAT_CLIENT_ID = "bc6a6d53-81d2-4ef2-990b-235763589ac4"
SNAPCHAT_CLIENT_SECRET = "a80e3b14de2b2b549c8d"
SNAPCHAT_REDIRECT_URI = "https://testing-within.onrender.com/oauth/snapchat/callback/"
SNAPCHAT_OAUTH_SCOPE = "snapchat-profile-api snapchat-marketing-api snapchat-offline-conversions-api"
